routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale?}',array('as'=>'set-locale','uses'=>'AppController@setLocale')); 
Route::get('/','HomesController@home')->name('/');
Route::get('portfolio','HomesController@portfolio')->name('portfolio');
Route::get('blog','HomesController@blog')->name('blog');
Route::get('blog-details','HomesController@blogdetail')->name('blog-details');
Route::post('/message','HomesController@message')->name('message');
Route::get('contact','HomesController@contact')->name('contact');
Route::get('website','HomesController@website')->name('website');
Route::get('seo','HomesController@seo')->name('seo');
Route::get('smm','HomesController@smm')->name('smm');
Route::get('logo','HomesController@logo')->name('logo');
Route::get('video','HomesController@video')->name('video');
Route::get('ppc','HomesController@ppc')->name('ppc');
Route::get('single','HomesController@single')->name('single');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'admin'], function () {
	Route::get('/devadmin','AdminController@admin')->name('/devadmin');
	Route::resource('/aportfolio','PortfolioController');
	Route::resource('/ablog','BlogController');
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table = 'blog';
    protected $fillable = [
        'title','lang', 'web_post','web_img','created_at'
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::orderBy('id','desc')->paginate(2);
        return view('backend.blog.index')->with('blogs',$blogs);
        // return view('backend.blog.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $validate = $request->validate([
            'title'=>'required',
            'lang'=>'required',
            'web_post'=>'required',
            'web_img'=>'required|file|max:5000',
        ]);
        // dd($request->title_en);die();
                if ($request->hasFile('web_img')) {
            $file = $request->file('web_img');
            $name = date('H-i-s').$file->getClientOriginalName();
            // $names = explode('.', $name);
            $file->move(public_path().'/frontend/images/blog/',$name);
            
        }
        $blogs = new Blog([
            'web_img'=>$name,
            'title'=>$request->title,
            'lang'=>$request->lang,
            'web_post'=>$request->web_post,
        ]);
        if ($blogs->save()) {
            return redirect('/ablog')->with('Success','Yangi blog qo`shildi!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog  = Blog::where('id',$id)->first();
        return view('backend.blog.blog-show',compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::find($id);
        return view('backend.blog.blog-edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'title'=>'required',
            'lang'=>'required',
            'web_post'=>'required',
            // 'web_img'=>'required|file|max:5000',
        ]);
        $blog = Blog::find($id);
        if ($request->hasFile('web_img')) {
            $file = $request->file('web_img');
            $name = date('H-i-s').$file->getClientOriginalName();
            // $names = explode('.', $name);
            $file->move(public_path().'/frontend/images/blog/',$name);
            
            $blog->web_img = $name;
        }
        

        $blog->title = $request->get('title');
        $blog->lang = $request->get('lang');
        $blog->web_post = $request->get('web_post');
        $blog->save();
        return redirect('/ablog')->with('success','Blog  o`zgartirildi');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $blog = Blog::find($id);

        $file = 'frontend/images/blog/'.$blog->web_img;
        if (file_exists($file)) {
            @unlink($file);
        }

        $blog->delete();
        return redirect('/ablog')->with('success', 'blog o`chirildi!');
    }
}

resources/views/backend/blog/blog-edit.blade.php
@extends('layouts.api')
@section('content')
<section id="main-content">
  <section class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="display-3">Update a Blogs</h5>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br /> 
                @endif

                <form method="post" action="{{ route('ablog.update', $blog->id) }}" enctype="multipart/form-data">
                    @method('PATCH') 
                    @csrf
                    <div class="form-group">
                        <label for="blog">blogni titleni O`zgartirish</label>
                        <div class="col-lg-10">
                            <textarea  class="form-control" name="title">{{ $blog->title }}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blog">blogni lang O`zgartirish</label>
                        <div class="col-lg-10">
                            <input type="text" name="lang" value="{{ $blog->lang }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="blog">blogni web_postni O`zgartirish</label>
                        <div class="col-lg-10">
                            <textarea id="editor5" class="form-control" name="web_post">{{ $blog->web_post }}</textarea>
                        </div>
                    </div>
                    

                    <div class="form-group">
                        <label for="blog">blogni image nomini O`zgartirish</label>
                        <div class="col-lg-10">
                            <input type="file" class="form-control" name="web_img" />
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary">Izmenit</button>

                </form>
            </div>
        </div>
    </div>
</section>
</section>
@endsection
@section('style')
@endsection
@section('script')
@endsection

resources/views/backend/blog/blog-show.blade.php
@extends('layouts.api')

@section('content')
<section id="main-content">
	<section class="wrapper">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h6>Id:{{$blog->id}} Title:
						{{$blog->title}}<br> Lang:
						{{$blog->lang}}<br> 
						{{$blog->yil}}</h6><br>web_post:
						{{$blog->web_post}}<br>
						<img src="{{ asset('frontend/images/blog/'.$blog->web_img) }}">
					</div>
				</div>
			</div>
		</section>
	</section>
	@endsection
	@section('style')
	@endsection
	@section('script')
	@endsection

resources/views/backend/blog/index.blade.php
@extends('layouts.api')

@section('content')
<!-- Basic Forms & Horizontal Forms-->
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-9">
			<section class="panel">
				<header class="panel-heading">
					Blog Kiritish:
				</header>
				<div class="panel-body">
					<form class="form-horizontal" action="{{ route('ablog.store') }}" method="post" name="form" enctype="multipart/form-data">
						{{csrf_field()}}

						<div class="form-group">
							<label  class="col-lg-2 control-label">title</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="title" ></textarea>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-lg-2 control-label">lang</label>
							<div class="col-lg-10">
								<input type="text" name="lang">
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">web_post</label>
							<div class="col-lg-10">
								<textarea id="editor5" class="form-control" name="web_post" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">web_img</label>
							<div class="col-lg-10">
								<input type="file" class="form-control" name="web_img" >
							</div>
						</div>



						<div class="form-group">
							<div class="col-lg-offset-2 col-lg-10">
								<button type="submit" class="btn btn-primary">Saxranit</button>
							</div>
						</div>
					</form>
				</div>
			</section>

		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<section class="panel">
				<header class="panel-heading">
					@if(isset($Success))
					{{$Success}}
					@endif;
				</header>
				@if(isset($blogs))
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-striped table-advance table-hover">
							<tbody>


								<tr>
									<th><i class="icon_string"></i>Title</th>
									<th><i class="icon_string"></i>Lang</th>
									<th><i class="icon_string"></i>Web_post</th>
									<th><i class="icon_picture"></i>Web_img</th>
									<th><i class="fa fa-eye"></i>Show</th>
									<th><i class="fa fa-edit"></i>Update</th>
									<th><i class="fa fa-trash"></i>Delete</th>
								</tr>
								@foreach ($blogs as $blog)

								<tr>



									<td>{{$blog->title}}</td>
									<td>{{$blog->lang}}</td>
									<td>{{$blog->web_post}}</td>
									<td>{{$blog->web_img}}</td>
									<div class="btn-group">
										<td>
											<a class="show-modal btn btn-info" href="{{ route('ablog.show',$blog->id) }}"><i class="fa fa-eye"></i></a>
										</td>

										<td>
											<a class="edit-modal btn btn-warning" href="{{ route('ablog.edit',$blog->id) }}"><i class="fa fa-edit"></i></a></td>
											<td>
												<form action="{{ route('ablog.destroy', $blog->id)}}" method="post">
													@csrf
													@method('DELETE')
													<button id="blog_sweetalert_delete" class="delete-modal btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
												</form>
											</td>

										</div>

									</tr>
									@endforeach
								</tbody>
							</table> 
						</div>
					</div>
							{{$blogs->links()}}
							@endif
						</section>
						@if(session()->get('success'))
						<div class="alert alert-success">
							{{ session()->get('success') }} 
						</div>
						@endif
					</div>
				</section>
			</section>

		</div>

		@endsection

		@section('style')
		@endsection

		@section('script')
		<script type="text/javascript">

       
</script>
		@endsection