routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('locale/{locale?}',array('as'=>'set-locale','uses'=>'AppController@setLocale')); 
Route::get('/','HomesController@home')->name('/');
Route::get('portfolio','HomesController@portfolio')->name('portfolio');
Route::get('blog','HomesController@blog')->name('blog');
Route::get('blog-details','HomesController@blogdetail')->name('blog-details');
Route::post('/message','HomesController@message')->name('message');
Route::get('contact','HomesController@contact')->name('contact');
Route::get('website','HomesController@website')->name('website');
Route::get('seo','HomesController@seo')->name('seo');
Route::get('smm','HomesController@smm')->name('smm');
Route::get('logo','HomesController@logo')->name('logo');
Route::get('video','HomesController@video')->name('video');
Route::get('ppc','HomesController@ppc')->name('ppc');
Route::get('single','HomesController@single')->name('single');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => 'admin'], function () {
	Route::get('/devadmin','AdminController@admin')->name('/devadmin');
	Route::resource('/aportfolio','PortfolioController');
	Route::resource('/ablog','BlogController');
});

app/Portfolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    protected $table = 'portfoli';
    protected $fillable = [
        'title', 'title_1', 'name','lang','service','sphere','technology','objective','description','category','img1','img2'
    ];
}

app/Http/Controllers/PortfolioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Portfolio;

class PortfolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $posts = Portfolio::orderBy('id','desc')->paginate(1);
        return view('backend.portfolio.index')->with('posts',$posts);;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'title'=>'required',
            'title_1'=>'required',
            'name'=>'required',
            'lang'=>'required',
            'service'=>'required',
            'sphere'=>'required',
            'technology'=>'required',
            'objective'=>'required',
            'description'=>'required',
            'category'=>'required',
            'img1'=>'required|file|max:5000',
            'img2'=>'required|file|max:5000',
        ]);
        if ($request->hasFile('img1')) {
            $file = $request->file('img1');
            $image = time().$file->getClientOriginalName();
            // $names = explode('.', $name);
            $file->move(public_path().'/frontend/images/portfoli/',$image);
            
        }
        if ($request->hasFile('img2')) {
            $file2 = $request->file('img2');
            $image2 = date('H-i-s').$file->getClientOriginalName();
            // $names = explode('.', $name);
            $file2->move(public_path().'/frontend/images/portfoli/',$image2);
            
        }
        $posts = new Portfolio([
            'img1'=>$image,
            'img2'=>$image2,
            'title'=>$request->title,
            'title_1'=>$request->title_1,
            'lang'=>$request->lang,
            'name'=>$request->name,
            'service'=>$request->service,
            'sphere'=>$request->sphere,
            'technology'=>$request->technology,
            'objective'=>$request->objective,
            'description'=>$request->description,
            'category'=>$request->category,
        ]);
        if ($posts->save()) {
            return redirect('/aportfolio')->with('Success','Yangi portfolio qo`shildi!');
        }
        else{
            return redirect('/aportfolio')->with('Success','Xatolik bor');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post  = Portfolio::where('id',$id)->first();
        return view('backend.portfolio.portfolio-show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Portfolio::find($id);
        return view('backend.portfolio.portfolio-edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = $request->validate([
            'title'=>'required',
            'title_1'=>'required',
            'lang'=>'required',
            'name'=>'required',
            'service'=>'required',
            'sphere'=>'required',
            'technology'=>'required',
            'objective'=>'required',
            'description'=>'required',
            'category'=>'required',
            // 'img1'=>'required|file|max:5000',
            // 'img2'=>'required|file|max:5000',
        ]);
        $post = Portfolio::find($id);
        if ($request->hasFile('img1')) {
            $file = $request->file('img1');
            $image = time().$file->getClientOriginalName();
            $file->move(public_path().'/frontend/images/portfoli/',$image);
            $post->img1 = $image;
        }

        if ($request->hasFile('img2')) {
            $file = $request->file('img2');
            $image2 = date('H-i-s').$file->getClientOriginalName();
            $file->move(public_path().'/frontend/images/portfoli/',$image2);
            $post->img2 = $image2;
        }
        

        $post->title = $request->get('title');
        $post->title_1 = $request->get('title_1');
        $post->lang = $request->get('lang');
        $post->name = $request->get('name');
        $post->service = $request->get('service');
        $post->sphere = $request->get('sphere');
        $post->technology = $request->get('technology');
        $post->objective = $request->get('objective');
        $post->description = $request->get('description');
        $post->category = $request->get('category');
        $post->save();
        return redirect('/aportfolio')->with('success','Portfolio  o`zgartirildi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Portfolio::find($id);

        $file = 'frontend/images/portfoli/'.$post->img1;
        $file2 = 'frontend/images/portfoli/'.$post->img2;
        if (file_exists($file)) {
            @unlink($file);
        }
        if (file_exists($file2)) {
            @unlink($file2);
        }

        $post->delete();
        return redirect('/aportfolio')->with('success', 'Portfolio o`chirildi!');
    }
}

resources/views/backend/portfolio/index.blade.php
	@extends('layouts.api')

	@section('content')
	<!-- Basic Forms & Horizontal Forms-->
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-9">
			<section class="panel">
				<header class="panel-heading">
					Portfolio Kiritish:
				</header>
				<div class="panel-body">
					<form class="form-horizontal" action="{{ route('aportfolio.store') }}" method="post" name="form" enctype="multipart/form-data">
						{{csrf_field()}}

						<div class="form-group">
							<label  class="col-lg-2 control-label">title</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="title" ></textarea>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-lg-2 control-label">title_1</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="title_1" ></textarea>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-lg-2 control-label">lang</label>
							<div class="col-lg-10">
								<input type="text" name="lang">
							</div>
						</div>
						<div class="form-group">
							<label  class="col-lg-2 control-label">name</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="name" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">service</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="service" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">sphere</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="sphere" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">technology</label>
							<div class="col-lg-10">
								<textarea  class="form-control" name="technology" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">objective</label>
							<div class="col-lg-10">
								<textarea id="editor7" class="form-control" name="objective" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">description</label>
							<div class="col-lg-10">
								<textarea id="editor8" class="form-control" name="description" ></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label  class="col-lg-2 control-label">category</label>
							<div class="col-lg-10">
								<textarea class="form-control" name="category" ></textarea>
							</div>
						</div>
						<div class="form-group">
							<label  class="col-lg-2 control-label">img1</label>
							<div class="col-lg-10">
								<input type="file" class="form-control" name="img1" >
							</div>
						</div>

						<div class="form-group">
							<label  class="col-lg-2 control-label">img2</label>
							<div class="col-lg-10">
								<input type="file" class="form-control" name="img2" >
							</div>
						</div>



						<div class="form-group">
							<div class="col-lg-offset-2 col-lg-10">
								<button type="submit" class="btn btn-primary">Saxranit</button>
							</div>
						</div>
					</form>
				</div>
			</section>

		</div>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<section class="panel">
				<header class="panel-heading">
					@if(isset($Success))
					{{$Success}}
					@endif;
				</header>
				@if(isset($posts))
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">

							<thead>
								<tr>
									<th><i class="icon_number"></i>Id</th>
									<th><i class="icon_string"></i>Title</th>
									<th><i class="icon_string"></i>Title_1</th>
									<th><i class="icon_string"></i>Name</th>
									<th><i class="icon_string"></i>Lang</th>
									<th><i class="icon_string"></i>Service</th>
									<th><i class="icon_string"></i>Sphere</th>
									<th><i class="icon_string"></i>Technology</th>
									<th><i class="icon_string"></i>Objective</th>
									<th><i class="icon_string"></i>Description</th>
									<th><i class="icon_string"></i>Category</th>
									<th><i class="icon_picture"></i>Img1</th>
									<th><i class="icon_picture"></i>Img2</th>
									<th><i class="fa fa-eye"></i>Show</th>
									<th><i class="fa fa-edit"></i>Update</th>
									<th><i class="fa fa-trash"></i>Delete</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($posts as $post)

								<tr>

									<td>{{$post->id}} </td>
									<td>{{$post->title}}</td>
									<td>{{$post->title_1}}</td>
									<td>{{$post->name}}</td>
									<td>{{$post->lang}}</td>
									<td>{{$post->service}}</td>
									<td>{{$post->sphere}}</td>
									<td>{{$post->technology}}</td>
									<td>{{$post->objective}}</td>
									<td>{{$post->description}}</td>
									<td>{{$post->category}}</td>
									<td>{{$post->img1}}</td>
									<td>{{$post->img2}}</td>
									<div class="btn-group">
										<td>
											<a class="btn btn-info" href="{{ route('aportfolio.show',$post->id) }}"><i class="fa fa-eye "></i></a>
										</td>

										<td>
											<a class="btn btn-warning" href="{{ route('aportfolio.edit',$post->id) }}"><i class="fa fa-edit"></i></a></td>
											<td>
												<form action="{{ route('aportfolio.destroy', $post->id)}}" method="post">
													@csrf
													@method('DELETE')
													<button id="post_sweetalert_delete" class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
												</form>
											</td>

										</div>

									</tr>
									@endforeach
								</tbody>
							</table> 
						</div>
					</div>
					{{$posts->links()}}
					@endif
				</section>
				@if(session()->get('success'))
				<div class="alert alert-success">
					{{ session()->get('success') }} 
				</div>
				@endif
			</div>
		</section>
	</section>
	</div>

	@endsection

	@section('style')
	@endsection

	@section('script')

	@endsection

resources/views/backend/portfolio/portfolio-edit.blade.php
@extends('layouts.api')
@section('content')
<section id="main-content">
  <section class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h5 class="display-3">Izmenit a Portfolio</h5>

                @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                <br /> 
                @endif

                <form method="post" action="{{ route('aportfolio.update', $post->id) }}" enctype="multipart/form-data">
                    @method('PATCH') 
                    @csrf
                   <div class="form-group">
                            <label  class="col-lg-2 control-label">title</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="title" >{{ $post->title }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">title_1</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="title_1" >{{ $post->title_1 }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">lang</label>
                            <div class="col-lg-10">
                                <input type="text" name="lang" value="{{ $post->lang }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">name</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="name" >{{ $post->name }}</textarea>
                            </div>
                        </div>
                       
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">service</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="service" >{{ $post->service }}</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">sphere</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="sphere" >{{ $post->sphere }}</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">technology</label>
                            <div class="col-lg-10">
                                <textarea class="form-control" name="technology" >{{ $post->technology }}</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">objective</label>
                            <div class="col-lg-10">
                                <textarea id="editor7" class="form-control" name="objective" >{{ $post->objective }}</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">description</label>
                            <div class="col-lg-10">
                                <textarea id="editor8" class="form-control" name="description" >{{ $post->description }}</textarea>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">category</label>
                            <div class="col-lg-10">
                                <textarea  class="form-control" name="category" >{{ $post->category }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label  class="col-lg-2 control-label">img1</label>
                            <div class="col-lg-10">
                                <input type="file" class="form-control" name="img1" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label  class="col-lg-2 control-label">img2</label>
                            <div class="col-lg-10">
                                <input type="file" class="form-control" name="img2" >
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button type="submit" class="btn btn-primary">Izmenit</button>
                            </div>
                        </div>

                </form>
            </div>
        </div>
    </div>
</section>
</section>
@endsection
@section('style')
@endsection
@section('script')
<script type="text/javascript">
        var editor1 = CKEDITOR.replace( 'editor1' );
        var editor11 = CKEDITOR.replace( 'editor11' );
        var editor2 = CKEDITOR.replace( 'editor2' );
        var editor3 = CKEDITOR.replace( 'editor3' );
        var editor31 = CKEDITOR.replace( 'editor31' );
        var editor4 = CKEDITOR.replace( 'editor4' );
        var editor41 = CKEDITOR.replace( 'editor41' );
        var editor5 = CKEDITOR.replace( 'editor5' );
        var editor51 = CKEDITOR.replace( 'editor51' );
        var editor6 = CKEDITOR.replace( 'editor6' );
        var editor61 = CKEDITOR.replace( 'editor61' );
        var editor7 = CKEDITOR.replace( 'editor7' );
        var editor71 = CKEDITOR.replace( 'editor71' );
        var editor8 = CKEDITOR.replace( 'editor8' );
        var editor81 = CKEDITOR.replace( 'editor81' );
        var editor9 = CKEDITOR.replace( 'editor9' );
</script>
@endsection

resources/views/backend/portfolio/portfolio-show.blade.php
@extends('layouts.api')

@section('content')
<section id="main-content">
	<section class="wrapper">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h6>Id:{{$post->id}} Title:
						{{$post->title}}<br><br> Title_1:
						{{$post->title_1}}<br><br> Name:
						{{$post->name}}<br><br> Service:
						{{$post->service}}<br><br>Sphere:
						{{$post->sphere}}<br><br>Technology:
						{{$post->technology}}<br><br>Objective:
						{{$post->objective}}<br><br>Description:
						{{$post->description}}<br><br>Category:
						{{$post->category}}</h6><br><br>
						<img src="{{ asset('frontend/images/portfoli/'.$post->img1) }}">
						<img src="{{ asset('frontend/images/portfoli/'.$post->img2) }}">
					</div>
				</div>
			</div>
		</section>
	</section>
	@endsection
	@section('style')
	@endsection
	@section('script')
	@endsection